---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: "on"
  network:
    - ["forwarded_port", {guest: 4000, host: 4000, auto_correct: true}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[nodejs-chef::package]
    attributes:
      dev_mode: true
