name 'nodejs-chef'
maintainer 'Ryan Hansohn'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures nodejs-chef'
long_description 'Installs/Configures nodejs-chef'
version '0.1.0'
